# Generated by Django 4.1 on 2022-08-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_ticket_numero_ticket2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
