# Generated by Django 4.1 on 2022-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
