# Generated by Django 4.1 on 2022-08-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
    ]
