# Generated by Django 4.1 on 2022-08-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_respuesta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='ticket',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='usuario.ticket'),
            preserve_default=False,
        ),
    ]
