# Generated by Django 4.1 on 2022-08-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_respuesta_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='ticket',
            new_name='numero_ticket',
        ),
    ]
