# Generated by Django 4.1 on 2022-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_rename_ticket_respuesta_numero_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
