# Generated by Django 4.1 on 2022-08-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_ticket_numero_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(max_length=10),
        ),
    ]
