# Generated by Django 4.1 on 2022-08-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='muestra_text',
        ),
    ]
