# Generated by Django 4.1 on 2022-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_remove_question_muestra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bottom_text',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='four_text',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='top_text',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='tree_text',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
