# Generated by Django 4.1 on 2022-08-17 18:08

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_respuesta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(default=usuario.models.numero, max_length=5),
        ),
    ]
