# Generated by Django 4.1 on 2022-09-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0019_alter_notificasion_estado_alter_notificasion_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificasion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificasion',
            name='mensaje',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificasion',
            name='tipo',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Retraso', 'Retraso'), ('Promocion', 'Promocion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificasion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
