# Generated by Django 4.1 on 2022-10-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_alter_notificasion_estado_alter_notificasion_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='nit',
            field=models.IntegerField(choices=[]),
        ),
    ]
