# Generated by Django 4.1 on 2022-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_alter_datos_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='nit',
            field=models.IntegerField(),
        ),
    ]
