# Generated by Django 4.1 on 2022-11-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_alter_datos_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={'verbose_name_plural': 'Datos'},
        ),
        migrations.AlterModelOptions(
            name='notificasion',
            options={'verbose_name_plural': 'Notificasiones'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='servicioactivo',
            options={'verbose_name_plural': 'Servicios Activos'},
        ),
    ]
